version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-tests
    volumes:
      - .:/mystuff
    networks:
      - n-tier

  db:
    image: sath89/oracle-12c
    container_name: db
    networks:
      - n-tier

networks:
  n-tier:
